-- HASAT TERİMLERİ GENİŞLETİLDİ: 134 → 323 (canlıya da yazılıyor)
--
-- NEDEN (ölçüm, 12.09.2026, canlı son 6 saat):
--     720 hasat turunun 426'sı (%59) TAMAMEN BOŞ döndü
--     hata / 429 hız sınırı .......... 0
--     bitmiş terim ................... 0
--     tur başına tavan 10 iken ortalama 2,33 karar
-- Yani darboğaz ne kaynak hız sınırı, ne ayar, ne de terimlerin "bitmesi":
-- 134 terimin madeni tükenmiş, aynı kararlar tekrar tekrar geliyor ve
-- mükerrer eleniyor. Cron'u sıklaştırmak yalnız BOŞ TUR sayısını artırırdı.
--
-- Her yeni terim, hiç dokunulmamış bir karar kümesinin kapısı. 189 yeni terim
-- eklendi (iş, aile, icra, gayrimenkul/imar, ticaret/fikri mülkiyet, sigorta,
-- sağlık, ceza, idare/vergi, usul, kişilik hakları/bilişim, tüketici).
--
-- NEDEN MIGRATION. Canlı hasat (pg_cron → harvest-tick) terimleri DOSYADAN
-- değil `ictihat_harvest_state` TABLOSUNDAN okuyor. scripts/ictihat-terms.txt
-- yalnız GitHub Actions yolundaki betiği besliyor ve o yol şu an kapalı
-- (SUPABASE_SERVICE_ROLE_KEY secret'ı boş). Dosyaya yazıp burayı atlamak,
-- "ekledim" sanıp hiçbir şey değiştirmemek olurdu.
--
-- ANAHTAR BİÇİMİ kodla aynı (bkz. harvest-tick, stateKey): emsal kaynağı
-- terimi ön eksiz, diğerleri "yargitay:" / "danistay:" ön ekiyle tutuyor.
--
-- MEVCUT TERİMLERE DOKUNULMAZ: on conflict do nothing. İlerlemiş sayfa
-- numaraları (next_page) ve öncelikler korunur — sıfırlamak, aylardır
-- yapılan taramayı baştan yaptırırdı.
--
-- BEKLENEN ÖLÇÜLEBİLİR ETKİ: boş tur oranı %59'dan düşmeli. Aynı raporla
-- (0121) birkaç saat sonra tekrar bakılmalı; düşmezse sebep terim sayısı
-- değildir ve bu migration'ın faydası YOKTUR — o zaman öyle yazılacak.

insert into public.ictihat_harvest_state (terim) values
  ('fazla mesai alacağı'),
  ('yargitay:fazla mesai alacağı'),
  ('danistay:fazla mesai alacağı'),
  ('hafta tatili ücreti'),
  ('yargitay:hafta tatili ücreti'),
  ('danistay:hafta tatili ücreti'),
  ('ulusal bayram genel tatil ücreti'),
  ('yargitay:ulusal bayram genel tatil ücreti'),
  ('danistay:ulusal bayram genel tatil ücreti'),
  ('yıllık izin ücreti alacağı'),
  ('yargitay:yıllık izin ücreti alacağı'),
  ('danistay:yıllık izin ücreti alacağı'),
  ('asgari geçim indirimi alacağı'),
  ('yargitay:asgari geçim indirimi alacağı'),
  ('danistay:asgari geçim indirimi alacağı'),
  ('iş kazası maddi tazminat'),
  ('yargitay:iş kazası maddi tazminat'),
  ('danistay:iş kazası maddi tazminat'),
  ('iş kazası manevi tazminat'),
  ('yargitay:iş kazası manevi tazminat'),
  ('danistay:iş kazası manevi tazminat'),
  ('meslek hastalığı tazminat'),
  ('yargitay:meslek hastalığı tazminat'),
  ('danistay:meslek hastalığı tazminat'),
  ('sigortalılığın tespiti'),
  ('yargitay:sigortalılığın tespiti'),
  ('danistay:sigortalılığın tespiti'),
  ('işverenin iş sağlığı güvenliği yükümlülüğü'),
  ('yargitay:işverenin iş sağlığı güvenliği yükümlülüğü'),
  ('danistay:işverenin iş sağlığı güvenliği yükümlülüğü'),
  ('işe iade sonrası boşta geçen süre'),
  ('yargitay:işe iade sonrası boşta geçen süre'),
  ('danistay:işe iade sonrası boşta geçen süre'),
  ('ibraname geçersizliği'),
  ('yargitay:ibraname geçersizliği'),
  ('danistay:ibraname geçersizliği'),
  ('rekabet yasağı sözleşmesi işçi'),
  ('yargitay:rekabet yasağı sözleşmesi işçi'),
  ('danistay:rekabet yasağı sözleşmesi işçi'),
  ('alt işveren asıl işveren ilişkisi'),
  ('yargitay:alt işveren asıl işveren ilişkisi'),
  ('danistay:alt işveren asıl işveren ilişkisi'),
  ('muvazaalı alt işverenlik'),
  ('yargitay:muvazaalı alt işverenlik'),
  ('danistay:muvazaalı alt işverenlik'),
  ('belirli süreli iş sözleşmesi'),
  ('yargitay:belirli süreli iş sözleşmesi'),
  ('danistay:belirli süreli iş sözleşmesi'),
  ('deneme süreli iş sözleşmesi'),
  ('yargitay:deneme süreli iş sözleşmesi'),
  ('danistay:deneme süreli iş sözleşmesi'),
  ('geçerli nedenle fesih işveren'),
  ('yargitay:geçerli nedenle fesih işveren'),
  ('danistay:geçerli nedenle fesih işveren'),
  ('performans düşüklüğü fesih'),
  ('yargitay:performans düşüklüğü fesih'),
  ('danistay:performans düşüklüğü fesih'),
  ('devamsızlık nedeniyle fesih'),
  ('yargitay:devamsızlık nedeniyle fesih'),
  ('danistay:devamsızlık nedeniyle fesih'),
  ('işyeri devri işçilik alacakları'),
  ('yargitay:işyeri devri işçilik alacakları'),
  ('danistay:işyeri devri işçilik alacakları'),
  ('velayetin değiştirilmesi'),
  ('yargitay:velayetin değiştirilmesi'),
  ('danistay:velayetin değiştirilmesi'),
  ('kişisel ilişki tesisi'),
  ('yargitay:kişisel ilişki tesisi'),
  ('danistay:kişisel ilişki tesisi'),
  ('tedbir nafakası'),
  ('yargitay:tedbir nafakası'),
  ('danistay:tedbir nafakası'),
  ('nafakanın artırılması'),
  ('yargitay:nafakanın artırılması'),
  ('danistay:nafakanın artırılması'),
  ('nafakanın kaldırılması'),
  ('yargitay:nafakanın kaldırılması'),
  ('danistay:nafakanın kaldırılması'),
  ('mal rejiminin tasfiyesi'),
  ('yargitay:mal rejiminin tasfiyesi'),
  ('danistay:mal rejiminin tasfiyesi'),
  ('katılma alacağı'),
  ('yargitay:katılma alacağı'),
  ('danistay:katılma alacağı'),
  ('değer artış payı alacağı'),
  ('yargitay:değer artış payı alacağı'),
  ('danistay:değer artış payı alacağı'),
  ('edinilmiş mallara katılma'),
  ('yargitay:edinilmiş mallara katılma'),
  ('danistay:edinilmiş mallara katılma'),
  ('aile konutu şerhi'),
  ('yargitay:aile konutu şerhi'),
  ('danistay:aile konutu şerhi'),
  ('evlilik birliğinin temelinden sarsılması'),
  ('yargitay:evlilik birliğinin temelinden sarsılması'),
  ('danistay:evlilik birliğinin temelinden sarsılması'),
  ('zina nedeniyle boşanma'),
  ('yargitay:zina nedeniyle boşanma'),
  ('danistay:zina nedeniyle boşanma'),
  ('terk nedeniyle boşanma'),
  ('yargitay:terk nedeniyle boşanma'),
  ('danistay:terk nedeniyle boşanma'),
  ('soybağının reddi'),
  ('yargitay:soybağının reddi'),
  ('danistay:soybağının reddi'),
  ('evlat edinmenin iptali'),
  ('yargitay:evlat edinmenin iptali'),
  ('danistay:evlat edinmenin iptali'),
  ('vesayet davası'),
  ('yargitay:vesayet davası'),
  ('danistay:vesayet davası'),
  ('kısıtlama davası'),
  ('yargitay:kısıtlama davası'),
  ('danistay:kısıtlama davası'),
  ('istihkak davası icra'),
  ('yargitay:istihkak davası icra'),
  ('danistay:istihkak davası icra'),
  ('şikayet icra mahkemesi'),
  ('yargitay:şikayet icra mahkemesi'),
  ('danistay:şikayet icra mahkemesi'),
  ('borca itiraz imzaya itiraz'),
  ('yargitay:borca itiraz imzaya itiraz'),
  ('danistay:borca itiraz imzaya itiraz'),
  ('kambiyo senetlerine özgü takip'),
  ('yargitay:kambiyo senetlerine özgü takip'),
  ('danistay:kambiyo senetlerine özgü takip'),
  ('ilamlı icra takibi'),
  ('yargitay:ilamlı icra takibi'),
  ('danistay:ilamlı icra takibi'),
  ('haczedilmezlik şikayeti'),
  ('yargitay:haczedilmezlik şikayeti'),
  ('danistay:haczedilmezlik şikayeti'),
  ('maaş haczi'),
  ('yargitay:maaş haczi'),
  ('danistay:maaş haczi'),
  ('konkordato talebi'),
  ('yargitay:konkordato talebi'),
  ('danistay:konkordato talebi'),
  ('iflasın ertelenmesi'),
  ('yargitay:iflasın ertelenmesi'),
  ('danistay:iflasın ertelenmesi'),
  ('aciz vesikası'),
  ('yargitay:aciz vesikası'),
  ('danistay:aciz vesikası'),
  ('rehnin paraya çevrilmesi'),
  ('yargitay:rehnin paraya çevrilmesi'),
  ('danistay:rehnin paraya çevrilmesi'),
  ('ipoteğin paraya çevrilmesi yoluyla takip'),
  ('yargitay:ipoteğin paraya çevrilmesi yoluyla takip'),
  ('danistay:ipoteğin paraya çevrilmesi yoluyla takip'),
  ('muris muvazaası tapu iptali'),
  ('yargitay:muris muvazaası tapu iptali'),
  ('danistay:muris muvazaası tapu iptali'),
  ('ortaklığın giderilmesi davası'),
  ('yargitay:ortaklığın giderilmesi davası'),
  ('danistay:ortaklığın giderilmesi davası'),
  ('izale-i şuyu'),
  ('yargitay:izale-i şuyu'),
  ('danistay:izale-i şuyu'),
  ('önalım hakkı şufa davası'),
  ('yargitay:önalım hakkı şufa davası'),
  ('danistay:önalım hakkı şufa davası'),
  ('kat mülkiyeti uyuşmazlığı'),
  ('yargitay:kat mülkiyeti uyuşmazlığı'),
  ('danistay:kat mülkiyeti uyuşmazlığı'),
  ('kat irtifakı'),
  ('yargitay:kat irtifakı'),
  ('danistay:kat irtifakı'),
  ('ortak alan kullanımı apartman'),
  ('yargitay:ortak alan kullanımı apartman'),
  ('danistay:ortak alan kullanımı apartman'),
  ('yönetim planına aykırılık'),
  ('yargitay:yönetim planına aykırılık'),
  ('danistay:yönetim planına aykırılık'),
  ('acele kamulaştırma'),
  ('yargitay:acele kamulaştırma'),
  ('danistay:acele kamulaştırma'),
  ('yapı ruhsatı iptali'),
  ('yargitay:yapı ruhsatı iptali'),
  ('danistay:yapı ruhsatı iptali'),
  ('kaçak yapı yıkım kararı'),
  ('yargitay:kaçak yapı yıkım kararı'),
  ('danistay:kaçak yapı yıkım kararı'),
  ('zilyetliğe dayalı tescil'),
  ('yargitay:zilyetliğe dayalı tescil'),
  ('danistay:zilyetliğe dayalı tescil'),
  ('kadastro tespitine itiraz'),
  ('yargitay:kadastro tespitine itiraz'),
  ('danistay:kadastro tespitine itiraz'),
  ('sınır tespiti davası'),
  ('yargitay:sınır tespiti davası'),
  ('danistay:sınır tespiti davası'),
  ('genel kurul kararının iptali'),
  ('yargitay:genel kurul kararının iptali'),
  ('danistay:genel kurul kararının iptali'),
  ('yönetim kurulu üyesinin sorumluluğu'),
  ('yargitay:yönetim kurulu üyesinin sorumluluğu'),
  ('danistay:yönetim kurulu üyesinin sorumluluğu'),
  ('şirket ortaklığından çıkma'),
  ('yargitay:şirket ortaklığından çıkma'),
  ('danistay:şirket ortaklığından çıkma'),
  ('haklı nedenle fesih şirket'),
  ('yargitay:haklı nedenle fesih şirket'),
  ('danistay:haklı nedenle fesih şirket'),
  ('sermaye artırımının iptali'),
  ('yargitay:sermaye artırımının iptali'),
  ('danistay:sermaye artırımının iptali'),
  ('çek iptali davası'),
  ('yargitay:çek iptali davası'),
  ('danistay:çek iptali davası'),
  ('bono kambiyo vasfı'),
  ('yargitay:bono kambiyo vasfı'),
  ('danistay:bono kambiyo vasfı'),
  ('ticari satımda ayıp ihbarı'),
  ('yargitay:ticari satımda ayıp ihbarı'),
  ('danistay:ticari satımda ayıp ihbarı'),
  ('acentelik sözleşmesi portföy tazminatı'),
  ('yargitay:acentelik sözleşmesi portföy tazminatı'),
  ('danistay:acentelik sözleşmesi portföy tazminatı'),
  ('franchise sözleşmesi uyuşmazlığı'),
  ('yargitay:franchise sözleşmesi uyuşmazlığı'),
  ('danistay:franchise sözleşmesi uyuşmazlığı'),
  ('distribütörlük sözleşmesi feshi'),
  ('yargitay:distribütörlük sözleşmesi feshi'),
  ('danistay:distribütörlük sözleşmesi feshi'),
  ('rekabet kurulu kararı iptali'),
  ('yargitay:rekabet kurulu kararı iptali'),
  ('danistay:rekabet kurulu kararı iptali'),
  ('marka hükümsüzlüğü davası'),
  ('yargitay:marka hükümsüzlüğü davası'),
  ('danistay:marka hükümsüzlüğü davası'),
  ('marka tecavüzü tazminat'),
  ('yargitay:marka tecavüzü tazminat'),
  ('danistay:marka tecavüzü tazminat'),
  ('patent hükümsüzlüğü'),
  ('yargitay:patent hükümsüzlüğü'),
  ('danistay:patent hükümsüzlüğü'),
  ('tasarım tecavüzü'),
  ('yargitay:tasarım tecavüzü'),
  ('danistay:tasarım tecavüzü'),
  ('telif hakkı ihlali tazminat'),
  ('yargitay:telif hakkı ihlali tazminat'),
  ('danistay:telif hakkı ihlali tazminat'),
  ('ticaret unvanına tecavüz'),
  ('yargitay:ticaret unvanına tecavüz'),
  ('danistay:ticaret unvanına tecavüz'),
  ('alan adı uyuşmazlığı'),
  ('yargitay:alan adı uyuşmazlığı'),
  ('danistay:alan adı uyuşmazlığı'),
  ('destekten yoksun kalma tazminatı'),
  ('yargitay:destekten yoksun kalma tazminatı'),
  ('danistay:destekten yoksun kalma tazminatı'),
  ('sürekli iş göremezlik tazminatı'),
  ('yargitay:sürekli iş göremezlik tazminatı'),
  ('danistay:sürekli iş göremezlik tazminatı'),
  ('geçici iş göremezlik'),
  ('yargitay:geçici iş göremezlik'),
  ('danistay:geçici iş göremezlik'),
  ('kusur oranı tespiti bilirkişi'),
  ('yargitay:kusur oranı tespiti bilirkişi'),
  ('danistay:kusur oranı tespiti bilirkişi'),
  ('trafik sigortası rücu davası'),
  ('yargitay:trafik sigortası rücu davası'),
  ('danistay:trafik sigortası rücu davası'),
  ('kasko sigortası tazminat'),
  ('yargitay:kasko sigortası tazminat'),
  ('danistay:kasko sigortası tazminat'),
  ('hayat sigortası ödeme talebi'),
  ('yargitay:hayat sigortası ödeme talebi'),
  ('danistay:hayat sigortası ödeme talebi'),
  ('sağlık sigortası ödememe'),
  ('yargitay:sağlık sigortası ödememe'),
  ('danistay:sağlık sigortası ödememe'),
  ('zorunlu deprem sigortası'),
  ('yargitay:zorunlu deprem sigortası'),
  ('danistay:zorunlu deprem sigortası'),
  ('sigorta tahkim komisyonu'),
  ('yargitay:sigorta tahkim komisyonu'),
  ('danistay:sigorta tahkim komisyonu'),
  ('rücuen tazminat sgk'),
  ('yargitay:rücuen tazminat sgk'),
  ('danistay:rücuen tazminat sgk'),
  ('manevi tazminat miktarının belirlenmesi'),
  ('yargitay:manevi tazminat miktarının belirlenmesi'),
  ('danistay:manevi tazminat miktarının belirlenmesi'),
  ('tıbbi malpraktis tazminat'),
  ('yargitay:tıbbi malpraktis tazminat'),
  ('danistay:tıbbi malpraktis tazminat'),
  ('hatalı tıbbi müdahale'),
  ('yargitay:hatalı tıbbi müdahale'),
  ('danistay:hatalı tıbbi müdahale'),
  ('aydınlatılmış onam'),
  ('yargitay:aydınlatılmış onam'),
  ('danistay:aydınlatılmış onam'),
  ('hastane hizmet kusuru'),
  ('yargitay:hastane hizmet kusuru'),
  ('danistay:hastane hizmet kusuru'),
  ('estetik ameliyat eser sözleşmesi'),
  ('yargitay:estetik ameliyat eser sözleşmesi'),
  ('danistay:estetik ameliyat eser sözleşmesi'),
  ('nitelikli dolandırıcılık'),
  ('yargitay:nitelikli dolandırıcılık'),
  ('danistay:nitelikli dolandırıcılık'),
  ('rüşvet suçu'),
  ('yargitay:rüşvet suçu'),
  ('danistay:rüşvet suçu'),
  ('irtikap suçu'),
  ('yargitay:irtikap suçu'),
  ('danistay:irtikap suçu'),
  ('özel belgede sahtecilik'),
  ('yargitay:özel belgede sahtecilik'),
  ('danistay:özel belgede sahtecilik'),
  ('mala zarar verme'),
  ('yargitay:mala zarar verme'),
  ('danistay:mala zarar verme'),
  ('konut dokunulmazlığının ihlali'),
  ('yargitay:konut dokunulmazlığının ihlali'),
  ('danistay:konut dokunulmazlığının ihlali'),
  ('şantaj suçu'),
  ('yargitay:şantaj suçu'),
  ('danistay:şantaj suçu'),
  ('kişisel verilerin hukuka aykırı ele geçirilmesi'),
  ('yargitay:kişisel verilerin hukuka aykırı ele geçirilmesi'),
  ('danistay:kişisel verilerin hukuka aykırı ele geçirilmesi'),
  ('bilişim sistemine girme'),
  ('yargitay:bilişim sistemine girme'),
  ('danistay:bilişim sistemine girme'),
  ('banka veya kredi kartının kötüye kullanılması'),
  ('yargitay:banka veya kredi kartının kötüye kullanılması'),
  ('danistay:banka veya kredi kartının kötüye kullanılması'),
  ('uyuşturucu ticareti suçu'),
  ('yargitay:uyuşturucu ticareti suçu'),
  ('danistay:uyuşturucu ticareti suçu'),
  ('kullanmak için uyuşturucu bulundurma'),
  ('yargitay:kullanmak için uyuşturucu bulundurma'),
  ('danistay:kullanmak için uyuşturucu bulundurma'),
  ('taksirle öldürme trafik'),
  ('yargitay:taksirle öldürme trafik'),
  ('danistay:taksirle öldürme trafik'),
  ('kasten öldürmeye teşebbüs'),
  ('yargitay:kasten öldürmeye teşebbüs'),
  ('danistay:kasten öldürmeye teşebbüs'),
  ('cinsel saldırı suçu'),
  ('yargitay:cinsel saldırı suçu'),
  ('danistay:cinsel saldırı suçu'),
  ('çocuğun cinsel istismarı'),
  ('yargitay:çocuğun cinsel istismarı'),
  ('danistay:çocuğun cinsel istismarı'),
  ('aile içi şiddet koruma kararı'),
  ('yargitay:aile içi şiddet koruma kararı'),
  ('danistay:aile içi şiddet koruma kararı'),
  ('6284 sayılı kanun tedbir'),
  ('yargitay:6284 sayılı kanun tedbir'),
  ('danistay:6284 sayılı kanun tedbir'),
  ('denetimli serbestlik'),
  ('yargitay:denetimli serbestlik'),
  ('danistay:denetimli serbestlik'),
  ('koşullu salıverilme'),
  ('yargitay:koşullu salıverilme'),
  ('danistay:koşullu salıverilme'),
  ('infazın ertelenmesi'),
  ('yargitay:infazın ertelenmesi'),
  ('danistay:infazın ertelenmesi'),
  ('adli para cezası taksitlendirme'),
  ('yargitay:adli para cezası taksitlendirme'),
  ('danistay:adli para cezası taksitlendirme'),
  ('etkin pişmanlık indirimi'),
  ('yargitay:etkin pişmanlık indirimi'),
  ('danistay:etkin pişmanlık indirimi'),
  ('haksız tahrik indirimi'),
  ('yargitay:haksız tahrik indirimi'),
  ('danistay:haksız tahrik indirimi'),
  ('meşru müdafaa ceza'),
  ('yargitay:meşru müdafaa ceza'),
  ('danistay:meşru müdafaa ceza'),
  ('disiplin cezasının iptali'),
  ('yargitay:disiplin cezasının iptali'),
  ('danistay:disiplin cezasının iptali'),
  ('memur görevden uzaklaştırma'),
  ('yargitay:memur görevden uzaklaştırma'),
  ('danistay:memur görevden uzaklaştırma'),
  ('atama işleminin iptali'),
  ('yargitay:atama işleminin iptali'),
  ('danistay:atama işleminin iptali'),
  ('naklen atama iptali'),
  ('yargitay:naklen atama iptali'),
  ('danistay:naklen atama iptali'),
  ('ihale iptali davası'),
  ('yargitay:ihale iptali davası'),
  ('danistay:ihale iptali davası'),
  ('kamu ihale kurumu kararı'),
  ('yargitay:kamu ihale kurumu kararı'),
  ('danistay:kamu ihale kurumu kararı'),
  ('belediye encümen kararı iptali'),
  ('yargitay:belediye encümen kararı iptali'),
  ('danistay:belediye encümen kararı iptali'),
  ('yıkım kararının iptali'),
  ('yargitay:yıkım kararının iptali'),
  ('danistay:yıkım kararının iptali'),
  ('ruhsat iptali işlemi'),
  ('yargitay:ruhsat iptali işlemi'),
  ('danistay:ruhsat iptali işlemi'),
  ('idari para cezasının iptali'),
  ('yargitay:idari para cezasının iptali'),
  ('danistay:idari para cezasının iptali'),
  ('usulsüzlük cezası iptali'),
  ('yargitay:usulsüzlük cezası iptali'),
  ('danistay:usulsüzlük cezası iptali'),
  ('katma değer vergisi iadesi'),
  ('yargitay:katma değer vergisi iadesi'),
  ('danistay:katma değer vergisi iadesi'),
  ('gelir vergisi tarhiyatı'),
  ('yargitay:gelir vergisi tarhiyatı'),
  ('danistay:gelir vergisi tarhiyatı'),
  ('kurumlar vergisi tarhiyatı'),
  ('yargitay:kurumlar vergisi tarhiyatı'),
  ('danistay:kurumlar vergisi tarhiyatı'),
  ('vergi tekniği raporu'),
  ('yargitay:vergi tekniği raporu'),
  ('danistay:vergi tekniği raporu'),
  ('ödeme emrine itiraz vergi'),
  ('yargitay:ödeme emrine itiraz vergi'),
  ('danistay:ödeme emrine itiraz vergi'),
  ('sahte fatura kullanma'),
  ('yargitay:sahte fatura kullanma'),
  ('danistay:sahte fatura kullanma'),
  ('emlak vergisi uyuşmazlığı'),
  ('yargitay:emlak vergisi uyuşmazlığı'),
  ('danistay:emlak vergisi uyuşmazlığı'),
  ('gümrük vergisi ceza kararı'),
  ('yargitay:gümrük vergisi ceza kararı'),
  ('danistay:gümrük vergisi ceza kararı'),
  ('sosyal güvenlik prim borcu'),
  ('yargitay:sosyal güvenlik prim borcu'),
  ('danistay:sosyal güvenlik prim borcu'),
  ('sgk idari para cezası'),
  ('yargitay:sgk idari para cezası'),
  ('danistay:sgk idari para cezası'),
  ('yürütmenin durdurulması talebi'),
  ('yargitay:yürütmenin durdurulması talebi'),
  ('danistay:yürütmenin durdurulması talebi'),
  ('istinaf başvuru süresi'),
  ('yargitay:istinaf başvuru süresi'),
  ('danistay:istinaf başvuru süresi'),
  ('temyiz süresi ve şartları'),
  ('yargitay:temyiz süresi ve şartları'),
  ('danistay:temyiz süresi ve şartları'),
  ('karar düzeltme talebi'),
  ('yargitay:karar düzeltme talebi'),
  ('danistay:karar düzeltme talebi'),
  ('yargılamanın yenilenmesi'),
  ('yargitay:yargılamanın yenilenmesi'),
  ('danistay:yargılamanın yenilenmesi'),
  ('eski hale getirme talebi'),
  ('yargitay:eski hale getirme talebi'),
  ('danistay:eski hale getirme talebi'),
  ('ihtiyati tedbir talebi'),
  ('yargitay:ihtiyati tedbir talebi'),
  ('danistay:ihtiyati tedbir talebi'),
  ('ihtiyati haciz talebi'),
  ('yargitay:ihtiyati haciz talebi'),
  ('danistay:ihtiyati haciz talebi'),
  ('delil tespiti talebi'),
  ('yargitay:delil tespiti talebi'),
  ('danistay:delil tespiti talebi'),
  ('bilirkişi raporuna itiraz'),
  ('yargitay:bilirkişi raporuna itiraz'),
  ('danistay:bilirkişi raporuna itiraz'),
  ('tanık beyanının değerlendirilmesi'),
  ('yargitay:tanık beyanının değerlendirilmesi'),
  ('danistay:tanık beyanının değerlendirilmesi'),
  ('yemin delili'),
  ('yargitay:yemin delili'),
  ('danistay:yemin delili'),
  ('usulden red kararı'),
  ('yargitay:usulden red kararı'),
  ('danistay:usulden red kararı'),
  ('dava şartı yokluğu'),
  ('yargitay:dava şartı yokluğu'),
  ('danistay:dava şartı yokluğu'),
  ('zamanaşımı def''i'),
  ('yargitay:zamanaşımı def''i'),
  ('danistay:zamanaşımı def''i'),
  ('hak düşürücü süre'),
  ('yargitay:hak düşürücü süre'),
  ('danistay:hak düşürücü süre'),
  ('görevli mahkemenin belirlenmesi'),
  ('yargitay:görevli mahkemenin belirlenmesi'),
  ('danistay:görevli mahkemenin belirlenmesi'),
  ('yetki itirazı'),
  ('yargitay:yetki itirazı'),
  ('danistay:yetki itirazı'),
  ('davaların birleştirilmesi'),
  ('yargitay:davaların birleştirilmesi'),
  ('danistay:davaların birleştirilmesi'),
  ('ıslah talebi'),
  ('yargitay:ıslah talebi'),
  ('danistay:ıslah talebi'),
  ('kısmi dava belirsiz alacak'),
  ('yargitay:kısmi dava belirsiz alacak'),
  ('danistay:kısmi dava belirsiz alacak'),
  ('arabuluculuk dava şartı'),
  ('yargitay:arabuluculuk dava şartı'),
  ('danistay:arabuluculuk dava şartı'),
  ('zorunlu arabuluculuk ticari dava'),
  ('yargitay:zorunlu arabuluculuk ticari dava'),
  ('danistay:zorunlu arabuluculuk ticari dava'),
  ('adli yardım talebi'),
  ('yargitay:adli yardım talebi'),
  ('danistay:adli yardım talebi'),
  ('vekalet ücretine itiraz'),
  ('yargitay:vekalet ücretine itiraz'),
  ('danistay:vekalet ücretine itiraz'),
  ('yargılama giderlerinin paylaştırılması'),
  ('yargitay:yargılama giderlerinin paylaştırılması'),
  ('danistay:yargılama giderlerinin paylaştırılması'),
  ('kişilik haklarına saldırı tazminat'),
  ('yargitay:kişilik haklarına saldırı tazminat'),
  ('danistay:kişilik haklarına saldırı tazminat'),
  ('basın yoluyla kişilik hakkı ihlali'),
  ('yargitay:basın yoluyla kişilik hakkı ihlali'),
  ('danistay:basın yoluyla kişilik hakkı ihlali'),
  ('internet içeriğinin kaldırılması'),
  ('yargitay:internet içeriğinin kaldırılması'),
  ('danistay:internet içeriğinin kaldırılması'),
  ('erişimin engellenmesi kararı'),
  ('yargitay:erişimin engellenmesi kararı'),
  ('danistay:erişimin engellenmesi kararı'),
  ('unutulma hakkı'),
  ('yargitay:unutulma hakkı'),
  ('danistay:unutulma hakkı'),
  ('kvkk kurul kararı iptali'),
  ('yargitay:kvkk kurul kararı iptali'),
  ('danistay:kvkk kurul kararı iptali'),
  ('kişisel verilerin korunması tazminat'),
  ('yargitay:kişisel verilerin korunması tazminat'),
  ('danistay:kişisel verilerin korunması tazminat'),
  ('konut kredisi erken kapama'),
  ('yargitay:konut kredisi erken kapama'),
  ('danistay:konut kredisi erken kapama'),
  ('banka masraf iadesi'),
  ('yargitay:banka masraf iadesi'),
  ('danistay:banka masraf iadesi'),
  ('kredi kartı aidat iadesi'),
  ('yargitay:kredi kartı aidat iadesi'),
  ('danistay:kredi kartı aidat iadesi'),
  ('abonelik sözleşmesi cayma'),
  ('yargitay:abonelik sözleşmesi cayma'),
  ('danistay:abonelik sözleşmesi cayma'),
  ('mesafeli satış cayma hakkı'),
  ('yargitay:mesafeli satış cayma hakkı'),
  ('danistay:mesafeli satış cayma hakkı'),
  ('devre tatil sözleşmesi iptali'),
  ('yargitay:devre tatil sözleşmesi iptali'),
  ('danistay:devre tatil sözleşmesi iptali'),
  ('paket tur sözleşmesi'),
  ('yargitay:paket tur sözleşmesi'),
  ('danistay:paket tur sözleşmesi'),
  ('ayıplı araç iade'),
  ('yargitay:ayıplı araç iade'),
  ('danistay:ayıplı araç iade'),
  ('garanti kapsamı uyuşmazlık'),
  ('yargitay:garanti kapsamı uyuşmazlık'),
  ('danistay:garanti kapsamı uyuşmazlık'),
  ('tüketici hakem heyeti kararına itiraz'),
  ('yargitay:tüketici hakem heyeti kararına itiraz'),
  ('danistay:tüketici hakem heyeti kararına itiraz')
on conflict (terim) do nothing;

-- Kaç satır eklendi? Beklenen: 189 terim × 3 kaynak = 567 (zaten varsa daha az).
select count(*) as toplam_terim_satiri from public.ictihat_harvest_state;
